# Default values for compss-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: oriolmac/compss-matmul
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 3.3

mqtt:
  enabled: false
  image:
    repository: eclipse-mosquitto
    tag: latest
    pullPolicy: IfNotPresent
  port: 1883
  nodePort: 31883

monitoring:
  enabled: true
  port: 15000
  redis:
    port: 6379
  prometheusUrl: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
  image:
    repository: oriolmac/compss-monitoring
    tag: "1.0"
    pullPolicy: Always
  servicemonitor:
    releaseName: prometheus
  namespace: monitoring
  node:

compss:
  # namespace: {}
  master:
    labels:
      node: master
    ports:
      name: ssh
    # local volume in node where the master is executed
    volume:
      localPath: /home/omartinez/results-helm  # it has to exist locally
      node: agx13

  worker:
    number: 1
    labels:
      node: worker
    resources:
      k8sCpuLimit: 4          # Real CPU limit assigned by Kubernetes to the pod
      compssStartingCpus: 2   # Number of CPUs COMPSs will start and use inside the container
      k8sMemoryLimit: 2       # Real memory limit (GB) assigned by Kubernetes to the pod

      # (W.I.P)
      #compssStartingMemory: 2    # Memory (GB) COMPSs will assume/use internally

    ports:
      name: ssh

  service:
    ssh: 22

app:
  context:
    folderPath: /home/omartinez/compss-matmul/matmul-extract
    file: matmul.py
  params:
    num_blocks: "3"
    elems_per_block: "512"
    number_iterations: "15"
