# Default values for compss-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: oriolmac/compss-matmul
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ascender

mqtt:
  enabled: false
  image:
    repository: eclipse-mosquitto
    tag: latest
    pullPolicy: IfNotPresent
  port: 1883
  nodePort: 31883

monitoring:
  enabled: true
  port: 15000
  redis:
    port: 6379
  prometheusUrl: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
  image:
    repository: oriolmac/compss-monitoring
    tag: "1.0"
    pullPolicy: Always
  servicemonitor:
    releaseName: prometheus
  namespace: monitoring
  node:

compss:
  cloud:
    minVms: 0
    maxVms: 4
    creationTime: 0

  # namespace: {}
  master:
    labels:
      node: master
    ports:
      name: ssh
    # local volume in node where the master is executed
    volume:
      localPath: /home/omartinez/results-heterogeneous  # it has to exist locally
      node: agx13

  worker:
    # HOMOGENEOUS CLUSTER
    #number: 2
    #resources:
    #  k8sCpuLimit: "4"          # **Currently deactivated** # Real CPU limit assigned by Kubernetes to the pod
    #  k8sMemoryLimit: "2Gi"     # **Currently deactivated** #  Real memory limit (GB) assigned by Kubernetes to the pods
    #  compssStartingCpus: "2"   # Number of CPUs COMPSs will start and use inside the container
    #  compssStartingMemory: "2" # Available memory COMPSs will start and use inside the container

    # HETEROGENEOUS CLUSTER
    workers:
      - hostname: agx13
        resources:
          k8sCpuLimit: "4"           # **Currently deactivated**
          k8sMemoryLimit: "2Gi"      # **Currently deactivated**
          compssStartingCpus: "2"
          compssStartingMemory: "2"
          
      - hostname: radxa
        resources:
          k8sCpuLimit: "1"           # **Currently deactivated**
          k8sMemoryLimit: "2Gi"      # **Currently deactivated**
          compssStartingCpus: "1"
          compssStartingMemory: "1"
        
    ports:
      name: ssh

  service:
    ssh: 22


app:
  context:
    folderPath: /home/omartinez/compss-matmul/matmul-extract
    file: matmul.py
  params:
    num_blocks: "3"
    elems_per_block: "512"
    number_iterations: "40"
