apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-results
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/{{ .Values.username }}/smart-city-compss/runs/exp   # mount path in the node 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.compss.master.volume.node }}