{{- $workerCount := .Values.compss.worker.number | int }}  
{{- range $i := until $workerCount }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $.Release.Name }}-worker-{{ $i }}
  labels:
    {{- include "compss-app.labels" $ | nindent 4 }}
    app: compss
    wf_id: {{ $.Release.Name }}
    role: worker-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compss
      wf_id: {{ $.Release.Name }}
      role: worker-{{ $i }}
  template:
    metadata:
      labels:
        app: compss 
        wf_id: {{ $.Release.Name }}
        role: worker-{{ $i }}
    spec:
      containers:
      - name: worker
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: [ "/usr/sbin/sshd",  "-D" ]
        resources:
          limits:
            memory: {{ $.Values.compss.worker.resources.memory }}G
            cpu: {{ $.Values.compss.worker.resources.k8sCpuLimit }}
        ports:
        - containerPort: 22
          name: 22-port
        - containerPort: 43001
          name: 43001-port
        - containerPort: 43002
          name: 43002-port
        - containerPort: 49049
          name: 49049-port
---
{{- end }}